### ISSUE TITLE
make 32 bit version of the game

### ISSUE THREAD

**Issue by jacklaplante** [jacklaplante/Skullborn#51]
maybe steam can handle this?

**Comment by Notarin** [comment]
Yes, steam supports launch dialogues. You place a 32-bit executable in the same directory as the 64-bit version, and choose which to launch with the steam dialogue.
![image](https://user-images.githubusercontent.com/25104390/145572004-fb54fec5-6383-41b2-9c8c-a60750ac7014.png)

**Comment by Notarin** [comment]
@jacklaplante Hi, i noticed you closed this. was this idea abandoned? Or was some other conclusion reached?

**Comment by jacklaplante** [comment]
ya conclusion was reached!

**Comment by Notarin** [comment]
What was it?

**Comment by jacklaplante** [comment]
I made a 32 bit version
